//! Filesystem-backed wiki page CRUD.
//!
//! Every page lives at `<app-data>/wiki/<path>` on disk and is mirrored
//! into the `wiki_pages` Postgres table on write so the [`super::search`]
//! and [`super::dashboard`] modules can query it via FTS without touching
//! the filesystem. The DB write is best-effort: if it fails we log and
//! keep going so the user's edit isn't lost.
//!
//! # Sub-modules
//!
//! - [`templates`] — static markdown / PoC scaffolding strings
//! - [`frontmatter`] — YAML frontmatter parsing + tree walking
//! - [`lifecycle`] — `wiki_init` / `wiki_reindex`
//! - [`crud`] — list / read / write / delete / rename / create_dir
//! - [`cve`] — `wiki_create_cve`

mod crud;
mod cve;
mod frontmatter;
mod lifecycle;
mod templates;

pub use frontmatter::WikiEntry;

// Re-export both the user-facing async commands and the `__cmd__*` shims
// generated by `#[tauri::command]` so `commands_registry` can register them
// via the existing `wiki::*` re-export in the parent module.
pub use crud::{
    wiki_create_dir, wiki_delete, wiki_list, wiki_read, wiki_rename, wiki_write,
    __cmd__wiki_create_dir, __cmd__wiki_delete, __cmd__wiki_list, __cmd__wiki_read,
    __cmd__wiki_rename, __cmd__wiki_write,
};
pub use cve::{wiki_create_cve, __cmd__wiki_create_cve};
pub use lifecycle::{wiki_init, wiki_reindex, __cmd__wiki_init, __cmd__wiki_reindex};

// Re-exports kept available to sibling wiki modules (search/dashboard) via
// `pub(in crate::tools::wiki)`.
pub(in crate::tools::wiki) use frontmatter::{extract_frontmatter, infer_category_from_path};
pub(in crate::tools::wiki) use templates::WIKI_CATEGORIES;
