pub mod ai;
pub mod cli_output;
pub mod compat;
mod error;
pub mod history;
mod indexer;
mod mcp;
mod models;
mod projects;
mod pty;
pub mod runtime;
mod settings;
mod sidecar;
mod state;
pub mod telemetry;
pub mod tools;
mod window_state;

mod app;

pub mod cli;

mod commands;

// Each line below brings every `#[tauri::command]` function from its
// domain module into the crate root so `tauri::generate_handler!` below can
// resolve unqualified command names. The `*` globs are intentional: the
// per-symbol lists (~70 names, kept verbatim with the previous explicit
// imports) drift every time a command is added, and each domain's `mod.rs`
// already curates its public surface via explicit `pub use ...` lines.
use ai::commands::*;
use commands::*;
use indexer::commands::*;
use mcp::*;
use models::commands::*;
use projects::commands::*;
use settings::commands::*;
use sidecar::commands::*;

/// Tauri application entry point for GUI mode.
///
/// Bootstraps process-level state (CLI args, env, telemetry, DB, settings,
/// history) via `app::bootstrap::*`, then delegates plugin/state/lifecycle
/// configuration to `app::tauri_app::configure_builder`. The giant
/// `tauri::generate_handler!` invocation has to live in this file because
/// Tauri's `#[command]` proc macro emits `__cmd__$name` macros via
/// `#[macro_export]`, which are only directly visible at the crate root.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run_gui() {
    app::bootstrap::apply_cli_workspace_arg();
    app::bootstrap::install_rustls_crypto_provider();
    app::bootstrap::load_dotenv();
    app::bootstrap::set_default_session_dir();

    let (_telemetry_guard, app_state) = app::bootstrap::init_telemetry_and_app_state();

    app::bootstrap::spawn_embedded_pg(app_state.db_ready.clone());
    app::bootstrap::seed_default_agent_files();

    let history_manager = app::bootstrap::init_history_manager_background();
    app::bootstrap::spawn_ensure_settings_file(app_state.settings_manager.clone());

    app::tauri_app::configure_builder(tauri::Builder::default(), app_state, history_manager)
        .invoke_handler(tauri::generate_handler![
            // PTY commands
            pty_create,
            pty_write,
            pty_resize,
            pty_destroy,
            pty_get_session,
            pty_get_foreground_process,
            set_active_terminal_session,
            // Completion commands
            list_path_completions,
            // Input classification (auto mode)
            classify_input,
            // Shell integration commands
            shell_integration_status,
            shell_integration_install,
            shell_integration_uninstall,
            get_git_branch,
            // Git commands
            git_status,
            git_diff,
            git_diff_staged,
            git_stage,
            git_unstage,
            git_commit,
            git_push,
            git_delete_worktree,
            // AI commands
            init_ai_agent,
            init_ai_agent_vertex,
            init_ai_agent_openai,
            init_ai_agent_unified,
            send_ai_prompt,
            execute_ai_tool,
            get_available_tools,
            list_sub_agents,
            get_sub_agent_model,
            set_sub_agent_model,
            shutdown_ai_agent,
            is_ai_initialized,
            // Isolated commit writer agent
            generate_commit_message,
            // Session-specific AI commands
            init_ai_session,
            shutdown_ai_session,
            cancel_ai_generation,
            is_ai_session_initialized,
            get_session_ai_config,
            send_ai_prompt_session,
            send_ai_prompt_with_attachments,
            get_vision_capabilities,
            clear_ai_conversation_session,
            get_ai_conversation_length_session,
            signal_frontend_ready,
            // Provider config commands
            get_openrouter_api_key,
            get_openai_api_key,
            get_project_settings,
            save_project_model,
            get_vertex_ai_config,
            load_env_file,
            update_ai_workspace,
            clear_ai_conversation,
            get_ai_conversation_length,
            restore_ai_conversation,
            // Session persistence commands
            list_ai_sessions,
            find_ai_session,
            load_ai_session,
            export_ai_session_transcript,
            set_ai_session_persistence,
            is_ai_session_persistence_enabled,
            finalize_ai_session,
            restore_ai_session,
            // Analytics / DB commands
            get_tool_call_stats,
            get_db_token_usage_stats,
            get_usage_by_agent,
            get_audit_log,
            search_memories,
            list_recent_memories,
            get_memory_count,
            // Agent definition management
            list_agent_definitions,
            read_agent_prompt,
            save_agent_definition,
            delete_agent_definition,
            seed_agents,
            // HITL commands
            get_approval_patterns,
            get_tool_approval_pattern,
            get_hitl_config,
            set_hitl_config,
            add_tool_always_allow,
            remove_tool_always_allow,
            reset_approval_patterns,
            respond_to_tool_approval,
            // Tool policy commands
            get_tool_policy_config,
            set_tool_policy_config,
            get_tool_policy,
            set_tool_policy,
            reset_tool_policies,
            enable_full_auto_mode,
            disable_full_auto_mode,
            is_full_auto_mode_enabled,
            // Agent mode commands
            get_agent_mode,
            set_agent_mode,
            save_project_agent_mode,
            set_use_agents,
            get_use_agents,
            set_execution_mode,
            get_execution_mode,
            // Debug commands
            get_api_request_stats,
            // Plan management commands
            get_plan,
            // Context management commands
            get_context_summary,
            get_token_usage_stats,
            get_token_alert_level,
            get_context_utilization,
            get_remaining_tokens,
            reset_context_manager,
            get_context_trim_config,
            is_context_management_enabled,
            retry_compaction,
            // Loop protection commands
            get_loop_protection_config,
            set_loop_protection_config,
            get_loop_detector_stats,
            is_loop_detection_enabled,
            disable_loop_detection,
            enable_loop_detection,
            reset_loop_detector,
            // Indexer commands
            init_indexer,
            is_indexer_initialized,
            get_indexer_workspace,
            get_indexed_file_count,
            get_all_indexed_files,
            index_file,
            index_directory,
            search_code,
            search_files,
            shutdown_indexer,
            // Codebase management commands
            list_indexed_codebases,
            add_indexed_codebase,
            remove_indexed_codebase,
            reindex_codebase,
            migrate_codebase_index,
            update_codebase_memory_file,
            detect_memory_files,
            // Home view commands
            list_projects_for_home,
            list_recent_directories,
            remove_recent_directory,
            // Worktree management commands
            list_git_branches,
            create_git_worktree,
            // Project config commands
            save_project,
            delete_project_config,
            list_project_configs,
            get_project_config,
            save_project_workspace,
            load_project_workspace,
            // Pentest project & file storage commands
            get_pentest_config,
            save_pentest_config,
            list_captures,
            list_capture_files,
            read_project_file,
            init_project_structure,
            clean_project_temp,
            // Prompt commands
            list_prompts,
            read_prompt,
            // Skill commands
            list_skills,
            read_skill,
            read_skill_body,
            list_skill_files,
            read_skill_file,
            save_skill,
            delete_skill,
            // Rule commands
            list_rules,
            read_rule_body,
            save_rule,
            delete_rule,
            // File commands
            list_workspace_files,
            list_directory,
            read_workspace_file,
            write_workspace_file,
            stat_workspace_file,
            read_file_as_base64,
            watch_file,
            unwatch_file,
            unwatch_all_files,
            // Theme commands
            list_themes,
            read_theme,
            save_theme,
            delete_theme,
            save_theme_asset,
            get_theme_asset_path,
            // History commands
            add_command_history,
            add_prompt_history,
            load_history,
            search_history,
            clear_history,
            // Recon tool commands
            run_recon_pipeline,
            check_recon_tools_cmd,
            // Settings commands
            get_settings,
            update_settings,
            get_setting,
            set_setting,
            reset_settings,
            settings_file_exists,
            get_settings_path,
            reload_settings,
            save_window_state,
            get_window_state,
            is_langfuse_active,
            get_telemetry_stats,
            // Model registry commands
            get_available_models,
            get_model_by_id,
            get_model_capabilities_command,
            get_providers,
            // Sidecar commands (simplified markdown-based)
            sidecar_status,
            sidecar_initialize,
            sidecar_start_session,
            sidecar_end_session,
            sidecar_current_session,
            sidecar_resume_session,
            sidecar_get_session_state,
            sidecar_get_session_log,
            sidecar_get_injectable_context,
            sidecar_get_session_meta,
            sidecar_list_sessions,
            sidecar_get_config,
            sidecar_set_config,
            sidecar_shutdown,
            // L2: Staged patches (git format-patch style)
            sidecar_get_staged_patches,
            sidecar_get_applied_patches,
            sidecar_get_patch,
            sidecar_discard_patch,
            sidecar_get_current_staged_patches,
            sidecar_apply_patch,
            sidecar_apply_all_patches,
            sidecar_regenerate_patch,
            sidecar_update_patch_message,
            // L3: Project artifacts (auto-maintained docs)
            sidecar_get_pending_artifacts,
            sidecar_get_applied_artifacts,
            sidecar_get_artifact,
            sidecar_discard_artifact,
            sidecar_preview_artifact,
            sidecar_get_current_pending_artifacts,
            sidecar_apply_artifact,
            sidecar_apply_all_artifacts,
            sidecar_regenerate_artifacts,
            write_frontend_log,
            // MCP (Model Context Protocol) commands
            mcp_list_servers,
            mcp_list_tools,
            mcp_get_config,
            mcp_is_project_trusted,
            mcp_trust_project_config,
            mcp_has_project_config,
            mcp_connect,
            mcp_disconnect,
            // Pentest tool management commands (ported from Golish)
            tools::pentest::pentest_scan_tools,
            tools::pentest::pentest_launch_tool,
            tools::pentest::pentest_kill_tool,
            tools::pentest::pentest_kill_all_tools,
            tools::pentest::pentest_search_tools,
            tools::pentest::pentest_get_command,
            tools::pentest::pentest_build_command,
            tools::pentest::pentest_check_runtime,
            tools::pentest::pentest_open_directory,
            tools::pentest::pentest_update_config,
            tools::pentest::pentest_get_config,
            tools::pentest::pentest_get_categories,
            tools::pentest::pentest_check_env_setup,
            tools::pentest::pentest_install_runtime,
            tools::pentest::pentest_cancel_runtime_install,
            tools::pentest::pentest_uninstall_runtime,
            tools::pentest::pentest_check_brew_outdated,
            tools::pentest::pentest_list_installed_ruby,
            tools::pentest::pentest_list_available_ruby,
            tools::pentest::pentest_install_ruby_version,
            tools::pentest::pentest_uninstall_ruby_version,
            tools::pentest::pentest_set_default_ruby,
            tools::pentest::pentest_create_file,
            tools::pentest::pentest_open_url,
            // GitHub API commands
            tools::pentest::pentest_fetch_github_releases,
            tools::pentest::pentest_fetch_github_release,
            tools::pentest::pentest_fetch_github_release_by_tag,
            tools::pentest::pentest_check_tool_updates,
            tools::pentest::pentest_fetch_github_repo_info,
            tools::pentest::pentest_fetch_github_readme,
            tools::pentest::pentest_analyze_github_tool,
            // Tool package management commands
            tools::pentest::pentest_create_tool_package,
            tools::pentest::pentest_update_tool,
            tools::pentest::pentest_update_tool_executable,
            tools::pentest::pentest_delete_backup,
            tools::pentest::pentest_delete_tool,
            tools::pentest::pentest_copy_to_toolpack,
            tools::pentest::pentest_download_and_extract,
            tools::pentest::pentest_cancel_download,
            tools::pentest::pentest_find_tool_executables,
            tools::pentest::pentest_rename_tool_dir,
            tools::pentest::pentest_uninstall_tool_files,
            tools::pentest::pentest_read_tool_config,
            tools::pentest::pentest_save_tool_config,
            tools::pentest::pentest_git_clone_tool,
            tools::pentest::pentest_pip_install_tool,
            tools::pentest::pentest_conda_install_tool,
            tools::pentest::pentest_resolve_python_path,
            tools::pentest::pentest_resolve_java_path,
            tools::pentest::pentest_install_requirements,
            tools::pentest::pentest_check_requirements,
            tools::pentest::pentest_list_dep_files,
            tools::pentest::pentest_install_dep_file,
            tools::pentest::pentest_browser_navigate,
            tools::pentest::pentest_browser_resize,
            tools::pentest::pentest_browser_hide,
            tools::pentest::pentest_browser_show,
            tools::pentest::pentest_browser_close,
            tools::pentest::pentest_browser_go_back,
            tools::pentest::pentest_browser_go_forward,
            // System proxy commands
            tools::pentest::pentest_set_system_proxy,
            tools::pentest::pentest_clear_system_proxy,
            tools::pentest::pentest_get_system_proxy,
            // Version management commands
            tools::pentest::pentest_list_installed_java,
            tools::pentest::pentest_list_available_java,
            tools::pentest::pentest_install_java_version,
            tools::pentest::pentest_uninstall_java_version,
            tools::pentest::pentest_set_default_java,
            tools::pentest::pentest_list_installed_node,
            tools::pentest::pentest_list_available_node,
            tools::pentest::pentest_install_node_version,
            tools::pentest::pentest_uninstall_node_version,
            tools::pentest::pentest_use_node_version,
            tools::pentest::pentest_list_python_envs,
            tools::pentest::pentest_list_available_python,
            tools::pentest::pentest_create_python_env,
            tools::pentest::pentest_delete_python_env,
            // Detached window commands
            tools::pentest::create_detached_window,
            tools::pentest::close_detached_window,
            // Skills CRUD
            tools::pentest::pentest_list_skills,
            tools::pentest::pentest_read_skill,
            tools::pentest::pentest_write_skill,
            tools::pentest::pentest_delete_skill,
            // ZAP integration
            tools::pentest::zap_start,
            tools::pentest::zap_stop,
            tools::pentest::zap_status,
            tools::pentest::zap_update_project,
            tools::pentest::zap_detect_path,
            tools::pentest::zap_set_path,
            tools::pentest::zap_get_history,
            tools::pentest::zap_get_history_count,
            tools::pentest::zap_get_message,
            tools::pentest::zap_start_scan,
            tools::pentest::zap_scan_progress,
            tools::pentest::zap_scan_message_count,
            tools::pentest::zap_stop_scan,
            tools::pentest::zap_pause_scan,
            tools::pentest::zap_resume_scan,
            tools::pentest::zap_list_scan_policies,
            tools::pentest::zap_batch_scan,
            tools::pentest::zap_get_alerts,
            tools::pentest::zap_get_scanners,
            tools::pentest::zap_set_scanners_enabled,
            tools::pentest::zap_get_alert_count,
            tools::pentest::zap_start_spider,
            tools::pentest::zap_spider_progress,
            tools::pentest::zap_stop_spider,
            tools::pentest::zap_send_request,
            tools::pentest::zap_get_hosts,
            tools::pentest::zap_new_session,
            tools::pentest::zap_save_session,
            tools::pentest::zap_sync_to_db,
            tools::pentest::zap_get_sitemap_data,
            tools::pentest::zap_download_root_cert,
            tools::pentest::zap_install_root_cert,
            tools::pentest::zap_api_call,
            // Wiki commands
            tools::wiki::wiki_init,
            tools::wiki::wiki_reindex,
            tools::wiki::wiki_list,
            tools::wiki::wiki_read,
            tools::wiki::wiki_write,
            tools::wiki::wiki_delete,
            tools::wiki::wiki_rename,
            tools::wiki::wiki_create_dir,
            tools::wiki::wiki_search,
            tools::wiki::wiki_search_db,
            tools::wiki::wiki_stats,
            tools::wiki::wiki_create_cve,
            tools::wiki::kb_research_load,
            tools::wiki::kb_research_save_turn,
            tools::wiki::kb_research_set_status,
            tools::wiki::kb_research_clear,
            tools::wiki::vuln_link_get_all,
            tools::wiki::vuln_link_get,
            tools::wiki::vuln_link_add_wiki,
            tools::wiki::vuln_link_remove_wiki,
            tools::wiki::vuln_link_add_poc,
            tools::wiki::vuln_link_update_poc,
            tools::wiki::vuln_link_remove_poc,
            tools::wiki::vuln_link_add_scan,
            tools::wiki::vuln_link_remove_scan,
            tools::wiki::vuln_link_add_poc_full,
            tools::wiki::vuln_poc_list_cves,
            tools::wiki::vuln_poc_list_unresearched,
            tools::wiki::vuln_poc_stats,
            tools::wiki::vuln_poc_set_verified,
            tools::wiki::wiki_pages_grouped,
            tools::wiki::wiki_pages_for_paths,
            tools::wiki::wiki_suggest_for_cve,
            tools::wiki::wiki_changelog_list,
            tools::wiki::wiki_backlinks,
            tools::wiki::wiki_stats_full,
            tools::wiki::wiki_orphan_pages,
            tools::targets::target_list,
            tools::targets::target_add,
            tools::targets::target_batch_add,
            tools::targets::target_update,
            tools::targets::target_update_status,
            tools::targets::target_delete,
            tools::targets::target_clear_all,
            tools::vault::vault_list,
            tools::vault::vault_add,
            tools::vault::vault_get_value,
            tools::vault::vault_update,
            tools::vault::vault_delete,
            tools::vault::vault_resolve,
            tools::vault::vault_validate,
            tools::vault::vault_update_status,
            tools::project_io::project_export,
            tools::project_io::project_import,
            tools::methodology::method_list_templates,
            tools::methodology::method_start_project,
            tools::methodology::method_list_projects,
            tools::methodology::method_load_project,
            tools::methodology::method_update_item,
            tools::methodology::method_delete_project,
            tools::recordings::recording_save,
            tools::recordings::recording_load,
            tools::recordings::recording_list,
            tools::recordings::recording_delete,
            tools::output_parser::output_parse,
            tools::output_parser::output_detect_tool,
            tools::output_parser::output_parse_and_store,
            tools::targets::directory_entry_list,
            tools::findings::findings_list,
            tools::findings::findings_add,
            tools::findings::findings_update,
            tools::findings::findings_delete,
            tools::findings::findings_import_parsed,
            tools::findings::findings_add_evidence,
            tools::findings::findings_remove_evidence,
            tools::findings::findings_evidence_path,
            tools::findings::findings_deduplicate,
            tools::findings::findings_for_host,
            tools::pipeline::pipeline_list,
            tools::pipeline::pipeline_save,
            tools::pipeline::pipeline_cancel,
            tools::pipeline::pipeline_delete,
            tools::pipeline::pipeline_load,
            tools::pipeline::pipeline_execute,
            tools::pipeline::pipeline_list_templates,
            tools::pipeline::pipeline_save_template,
            tools::pipeline::pipeline_delete_template,
            tools::scan_queue::scan_queue_list,
            tools::scan_queue::scan_queue_upsert,
            tools::scan_queue::scan_queue_save_all,
            tools::scan_queue::scan_queue_remove,
            tools::scan_queue::scan_queue_clear_completed,
            tools::custom_rules::custom_rules_list,
            tools::custom_rules::custom_rules_upsert,
            tools::custom_rules::custom_rules_save_all,
            tools::custom_rules::custom_rules_delete,
            tools::notes::notes_list,
            tools::notes::notes_add,
            tools::notes::notes_update,
            tools::notes::notes_delete,
            tools::audit::audit_log,
            tools::audit::audit_list,
            tools::audit::audit_clear,
            tools::audit::agent_logs_list,
            tools::audit::terminal_logs_list,
            tools::audit::search_logs_list,
            tools::audit::passive_scans_global,
            tools::wordlists::wordlist_list,
            tools::wordlists::wordlist_import,
            tools::wordlists::wordlist_delete,
            tools::wordlists::wordlist_deduplicate,
            tools::wordlists::wordlist_merge,
            tools::wordlists::wordlist_preview,
            tools::wordlists::wordlist_path,
            tools::vuln_intel::intel_list_feeds,
            tools::vuln_intel::intel_add_feed,
            tools::vuln_intel::intel_toggle_feed,
            tools::vuln_intel::intel_delete_feed,
            tools::vuln_intel::intel_fetch,
            tools::vuln_intel::intel_fetch_page,
            tools::vuln_intel::intel_get_cached,
            tools::vuln_intel::intel_search,
            tools::vuln_intel::intel_search_remote,
            tools::vuln_intel::intel_search_remote_page,
            tools::vuln_intel::intel_match_targets,
            tools::vuln_intel::intel_search_github_poc,
            tools::vuln_intel::intel_search_nuclei_templates,
            tools::vuln_intel::intel_batch_search_nuclei_templates,
            tools::vuln_intel::intel_discover_all_nuclei,
            // Conversation persistence (replaces workspace.json)
            tools::conversation_store::conv_save,
            tools::conversation_store::conv_delete,
            tools::conversation_store::conv_list,
            tools::conversation_store::conv_save_messages,
            tools::conversation_store::conv_load_messages,
            tools::conversation_store::conv_save_timeline,
            tools::conversation_store::conv_load_timeline,
            tools::conversation_store::conv_save_terminal_state,
            tools::conversation_store::conv_load_terminal_states,
            tools::conversation_store::conv_save_preferences,
            tools::conversation_store::conv_load_preferences,
            tools::conversation_store::conv_save_batch,
            // Execution plans
            tools::execution_plans::plan_create,
            tools::execution_plans::plan_get,
            tools::execution_plans::plan_list,
            tools::execution_plans::plan_list_active,
            tools::execution_plans::plan_update_steps,
            tools::execution_plans::plan_update_status,
            tools::execution_plans::plan_update_context,
            tools::execution_plans::plan_delete,
            // Security analysis
            tools::security_analysis::oplog_list,
            tools::security_analysis::oplog_list_by_target,
            tools::security_analysis::oplog_list_by_type,
            tools::security_analysis::oplog_search,
            tools::security_analysis::oplog_count,
            tools::security_analysis::target_assets_list,
            tools::security_analysis::api_endpoints_list,
            tools::security_analysis::api_endpoints_untested,
            tools::security_analysis::fingerprints_list,
            tools::security_analysis::js_analysis_list,
            tools::security_analysis::passive_scans_list,
            tools::security_analysis::passive_scans_by_url,
            tools::security_analysis::passive_scans_vulnerable,
            tools::security_analysis::passive_scans_stats,
            tools::security_analysis::target_security_overview,
            // Scan runner (WhatWeb, Nuclei targeted, feroxbuster)
            tools::scan_runner::scan_whatweb,
            tools::scan_runner::match_pocs_for_target,
            tools::scan_runner::scan_nuclei_targeted,
            tools::scan_runner::nuclei_cancel,
            tools::scan_runner::scan_feroxbuster,
            tools::scan_runner::get_zap_discovered_paths,
            // Sensitive file scanner
            tools::sensitive_scan::sensitive_scan_start,
            tools::sensitive_scan::sensitive_scan_stop,
            tools::sensitive_scan::sensitive_scan_status,
            tools::sensitive_scan::sensitive_scan_results,
            tools::sensitive_scan::sensitive_scan_clear,
            tools::sensitive_scan::sensitive_scan_confirm,
            tools::sensitive_scan::sensitive_scan_default_paths,
            tools::sensitive_scan::sensitive_scan_apply_verdicts,
            // IME switching (macOS)
            ime_get_source,
            ime_set_source,
        ])
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app_handle, event| {
            crate::app::window_lifecycle::handle_run_event(app_handle, event);
        });
}
