import { ANTHROPIC_PROVIDER_GROUP, ANTHROPIC_PROVIDER_GROUP_NESTED } from "./anthropic";
import { GEMINI_PROVIDER_GROUP, GEMINI_PROVIDER_GROUP_NESTED } from "./gemini";
import { GROQ_PROVIDER_GROUP, GROQ_PROVIDER_GROUP_NESTED } from "./groq";
import { NVIDIA_PROVIDER_GROUP, NVIDIA_PROVIDER_GROUP_NESTED } from "./nvidia";
import { OLLAMA_PROVIDER_GROUP, OLLAMA_PROVIDER_GROUP_NESTED } from "./ollama";
import { OPENAI_PROVIDER_GROUP, OPENAI_PROVIDER_GROUP_NESTED } from "./openai";
import { OPENROUTER_PROVIDER_GROUP, OPENROUTER_PROVIDER_GROUP_NESTED } from "./openrouter";
import type { ProviderGroup, ProviderGroupNested } from "./types";
import {
  VERTEX_AI_PROVIDER_GROUP,
  VERTEX_AI_PROVIDER_GROUP_NESTED,
  VERTEX_GEMINI_PROVIDER_GROUP,
  VERTEX_GEMINI_PROVIDER_GROUP_NESTED,
} from "./vertex";
import { XAI_PROVIDER_GROUP, XAI_PROVIDER_GROUP_NESTED } from "./xai";
import { ZAI_SDK_PROVIDER_GROUP, ZAI_SDK_PROVIDER_GROUP_NESTED } from "./zai";

/**
 * All available providers and their models.
 * Sorted alphabetically by provider name.
 */
export const PROVIDER_GROUPS: ProviderGroup[] = [
  ANTHROPIC_PROVIDER_GROUP,
  GEMINI_PROVIDER_GROUP,
  GROQ_PROVIDER_GROUP,
  OLLAMA_PROVIDER_GROUP,
  OPENAI_PROVIDER_GROUP,
  OPENROUTER_PROVIDER_GROUP,
  VERTEX_AI_PROVIDER_GROUP,
  VERTEX_GEMINI_PROVIDER_GROUP,
  XAI_PROVIDER_GROUP,
  ZAI_SDK_PROVIDER_GROUP,
  NVIDIA_PROVIDER_GROUP,
];

/**
 * Nested provider groups with sub-menus for models with reasoning effort variants.
 * Use this for the ModelSelector UI to show compact grouped menus.
 */
export const PROVIDER_GROUPS_NESTED: ProviderGroupNested[] = [
  ANTHROPIC_PROVIDER_GROUP_NESTED,
  GEMINI_PROVIDER_GROUP_NESTED,
  GROQ_PROVIDER_GROUP_NESTED,
  OLLAMA_PROVIDER_GROUP_NESTED,
  OPENAI_PROVIDER_GROUP_NESTED,
  OPENROUTER_PROVIDER_GROUP_NESTED,
  VERTEX_AI_PROVIDER_GROUP_NESTED,
  VERTEX_GEMINI_PROVIDER_GROUP_NESTED,
  XAI_PROVIDER_GROUP_NESTED,
  ZAI_SDK_PROVIDER_GROUP_NESTED,
  NVIDIA_PROVIDER_GROUP_NESTED,
];
