/**
 * Plan / task-step types.
 *
 * These mirror the Rust definitions in `backend/crates/golish-agent-kit`
 * (`PlanStep`, `PlanSummary`, `TaskPlan`, `StepStatus`). They were
 * previously generated by `ts-rs` into `frontend/lib/generated/` but the
 * codegen pipeline is being retired (M2.5) — definitions are inlined here
 * as the canonical frontend source. Keep the field names and union
 * values in sync with the Rust types if you change either side.
 */

/**
 * Status of a plan step.
 */
export type StepStatus = "pending" | "in_progress" | "completed" | "cancelled" | "failed";

/**
 * Why a step failed — borrowed from the PentAGI refiner taxonomy.
 * Mirrors the Rust `golish_core::plan::FailureKind` enum.
 * See docs/design/2026-05-17-refiner-patch-protocol.md.
 */
export type FailureKind = "technical" | "environmental" | "conceptual" | "external";

/**
 * A single step in the plan.
 */
export interface PlanStep {
  /**
   * Stable unique identifier for this step (UUID).
   * Persists across plan updates so tool executions remain linked.
   */
  id?: string | null;
  /**
   * Description of what this step accomplishes.
   */
  step: string;
  /**
   * Current status of this step.
   */
  status: StepStatus;
  /**
   * Optional failure category when `status === "failed"`.
   * Omitted on the wire when None on the backend.
   */
  failure_kind?: FailureKind | null;
}

/**
 * Summary statistics for a plan.
 */
export interface PlanSummary {
  total: number;
  completed: number;
  in_progress: number;
  pending: number;
}

/**
 * A complete task plan with steps and metadata.
 */
export interface TaskPlan {
  /**
   * Optional high-level explanation of the plan.
   */
  explanation: string | null;
  /**
   * The steps in the plan.
   */
  steps: PlanStep[];
  /**
   * Summary statistics.
   */
  summary: PlanSummary;
  /**
   * Version number (increments on each update).
   */
  version: number;
  /**
   * When the plan was last updated.
   */
  updated_at: string;
}

export interface RetiredPlan {
  plan: TaskPlan;
  messageId: string;
  retiredAt: string;
}
