// AUTO-GENERATED by `golish-codegen`. DO NOT EDIT.
// Run `just generate-ipc` to refresh; see ADR-0009 Phase 3.
//
// M2 status: this file is generated **side-by-side** with the
// hand-written `commands_registry.rs` for cross-validation; it is
// *not* yet `include!`-d into `lib.rs`. M3 will perform the swap.

use crate::commands_facade::ai::*;
use crate::commands_facade::findings::*;
use crate::commands_facade::git_pty::*;
use crate::commands_facade::indexer::*;
use crate::commands_facade::mcp::*;
use crate::commands_facade::pentest::*;
use crate::commands_facade::pipeline::*;
use crate::commands_facade::settings::*;
use crate::commands_facade::sidecar::*;
use crate::commands_facade::vault::*;
use crate::commands_facade::vuln_intel::*;
use crate::commands_facade::wiki::*;
use crate::commands_facade::workspace::*;

/// Tauri `invoke_handler` installer generated from
/// `#[tauri::command]` annotations across the workspace.
#[allow(dead_code)]
pub fn install_handlers_generated(
    builder: tauri::Builder<tauri::Wry>,
) -> tauri::Builder<tauri::Wry> {
    builder.invoke_handler(tauri::generate_handler![
        // ── ai (98 commands) ──
        add_tool_always_allow, cancel_ai_generation, check_recon_tools_cmd, clear_ai_conversation,
        clear_ai_conversation_session, delete_agent_definition, disable_full_auto_mode, disable_loop_detection,
        enable_full_auto_mode, enable_loop_detection, execute_ai_tool, export_ai_session_transcript,
        finalize_ai_session, find_ai_session, generate_commit_message, generate_conversation_summary,
        get_agent_mode, get_ai_conversation_length, get_ai_conversation_length_session, get_api_request_stats,
        get_approval_patterns, get_audit_log, get_available_tools, get_context_summary,
        get_context_trim_config, get_context_utilization, get_db_token_usage_stats, get_execution_mode,
        get_hitl_config, get_loop_detector_stats, get_loop_protection_config, get_memory_count,
        get_openai_api_key, get_openrouter_api_key, get_plan, get_project_settings,
        get_remaining_tokens, get_session_ai_config, get_sub_agent_model, get_token_alert_level,
        get_token_usage_stats, get_tool_approval_pattern, get_tool_call_stats, get_tool_policy,
        get_tool_policy_config, get_usage_by_agent, get_use_agents, get_vertex_ai_config,
        get_vision_capabilities, init_ai_agent, init_ai_agent_openai, init_ai_agent_unified,
        init_ai_agent_vertex, init_ai_session, is_ai_initialized, is_ai_session_initialized,
        is_ai_session_persistence_enabled, is_context_management_enabled, is_full_auto_mode_enabled, is_loop_detection_enabled,
        list_agent_definitions, list_ai_sessions, list_recent_memories, list_sub_agents,
        load_ai_session, load_env_file, read_agent_prompt, remove_tool_always_allow,
        reset_approval_patterns, reset_context_manager, reset_loop_detector, reset_tool_policies,
        respond_to_tool_approval, restore_ai_conversation, restore_ai_session, retry_compaction,
        run_recon_pipeline, save_agent_definition, save_project_agent_mode, save_project_model,
        search_memories, seed_agents, send_ai_prompt, send_ai_prompt_session,
        send_ai_prompt_with_attachments, set_agent_mode, set_ai_session_persistence, set_execution_mode,
        set_hitl_config, set_loop_protection_config, set_sub_agent_model, set_tool_policy,
        set_tool_policy_config, set_use_agents, shutdown_ai_agent, shutdown_ai_session,
        signal_frontend_ready, update_ai_workspace,
        // ── findings (10 commands) ──
        findings_add, findings_add_evidence, findings_deduplicate, findings_delete,
        findings_evidence_path, findings_for_host, findings_import_parsed, findings_list,
        findings_remove_evidence, findings_update,
        // ── git_pty (34 commands) ──
        add_command_history, add_prompt_history, classify_input, clear_history,
        delete_theme, get_git_branch, get_theme_asset_path, git_commit,
        git_delete_worktree, git_diff, git_diff_staged, git_push,
        git_stage, git_status, git_unstage, ime_get_source,
        ime_set_source, list_themes, load_history, pty_create,
        pty_destroy, pty_get_foreground_process, pty_get_session, pty_resize,
        pty_write, read_theme, save_theme, save_theme_asset,
        search_history, set_active_terminal_session, shell_integration_install, shell_integration_status,
        shell_integration_uninstall, write_frontend_log,
        // ── indexer (22 commands) ──
        add_indexed_codebase, create_git_worktree, detect_memory_files, get_all_indexed_files,
        get_indexed_file_count, get_indexer_workspace, index_directory, index_file,
        init_indexer, is_indexer_initialized, list_git_branches, list_indexed_codebases,
        list_projects_for_home, list_recent_directories, migrate_codebase_index, reindex_codebase,
        remove_indexed_codebase, remove_recent_directory, search_code, search_files,
        shutdown_indexer, update_codebase_memory_file,
        // ── mcp (8 commands) ──
        mcp_connect, mcp_disconnect, mcp_get_config, mcp_has_project_config,
        mcp_is_project_trusted, mcp_list_servers, mcp_list_tools, mcp_trust_project_config,
        // ── pentest (124 commands) ──
        close_detached_window, create_detached_window, pentest_analyze_github_tool, pentest_browser_close,
        pentest_browser_go_back, pentest_browser_go_forward, pentest_browser_hide, pentest_browser_navigate,
        pentest_browser_resize, pentest_browser_show, pentest_build_command, pentest_cancel_download,
        pentest_cancel_runtime_install, pentest_check_brew_outdated, pentest_check_env_setup, pentest_check_requirements,
        pentest_check_runtime, pentest_check_tool_executable_permission, pentest_check_tool_updates, pentest_check_tools_executable_permissions,
        pentest_clear_system_proxy, pentest_conda_install_tool, pentest_copy_to_toolpack, pentest_create_file,
        pentest_create_python_env, pentest_create_tool_package, pentest_delete_backup, pentest_delete_python_env,
        pentest_delete_skill, pentest_delete_tool, pentest_download_and_extract, pentest_fetch_github_readme,
        pentest_fetch_github_release, pentest_fetch_github_release_by_tag, pentest_fetch_github_releases, pentest_fetch_github_repo_info,
        pentest_find_tool_executables, pentest_fix_tool_executable_permission, pentest_get_categories, pentest_get_command,
        pentest_get_config, pentest_get_system_proxy, pentest_git_clone_tool, pentest_install_dep_file,
        pentest_install_java_version, pentest_install_node_version, pentest_install_requirements, pentest_install_ruby_version,
        pentest_install_runtime, pentest_kill_all_tools, pentest_kill_tool, pentest_launch_tool,
        pentest_list_available_java, pentest_list_available_node, pentest_list_available_python, pentest_list_available_ruby,
        pentest_list_dep_files, pentest_list_installed_java, pentest_list_installed_node, pentest_list_installed_ruby,
        pentest_list_python_envs, pentest_list_skills, pentest_list_tool_dir_files, pentest_open_directory,
        pentest_open_url, pentest_pip_install, pentest_pip_install_tool, pentest_pip_uninstall,
        pentest_read_skill, pentest_read_tool_config, pentest_rename_tool_dir, pentest_resolve_java_path,
        pentest_resolve_python_path, pentest_save_tool_config, pentest_scan_tools, pentest_search_tools,
        pentest_set_default_java, pentest_set_default_ruby, pentest_set_system_proxy, pentest_uninstall_brew_pkg,
        pentest_uninstall_gem_pkg, pentest_uninstall_java_version, pentest_uninstall_node_version, pentest_uninstall_ruby_version,
        pentest_uninstall_runtime, pentest_uninstall_tool_files, pentest_update_config, pentest_update_tool,
        pentest_update_tool_executable, pentest_use_node_version, pentest_write_skill, zap_api_call,
        zap_batch_scan, zap_detect_path, zap_download_root_cert, zap_get_alert_count,
        zap_get_alerts, zap_get_history, zap_get_history_count, zap_get_hosts,
        zap_get_message, zap_get_scanners, zap_get_sitemap_data, zap_install_root_cert,
        zap_list_scan_policies, zap_new_session, zap_pause_scan, zap_resume_scan,
        zap_save_session, zap_scan_message_count, zap_scan_progress, zap_send_request,
        zap_set_path, zap_set_scanners_enabled, zap_spider_progress, zap_start,
        zap_start_scan, zap_start_spider, zap_status, zap_stop,
        zap_stop_scan, zap_stop_spider, zap_sync_to_db, zap_update_project,
        // ── pipeline (9 commands) ──
        pipeline_cancel, pipeline_delete, pipeline_delete_template, pipeline_execute,
        pipeline_list, pipeline_list_templates, pipeline_load, pipeline_save,
        pipeline_save_template,
        // ── settings (16 commands) ──
        get_available_models, get_model_by_id, get_model_capabilities_command, get_providers,
        get_setting, get_settings, get_settings_path, get_telemetry_stats,
        get_window_state, is_langfuse_active, reload_settings, reset_settings,
        save_window_state, set_setting, settings_file_exists, update_settings,
        // ── sidecar (32 commands) ──
        sidecar_apply_all_artifacts, sidecar_apply_all_patches, sidecar_apply_artifact, sidecar_apply_patch,
        sidecar_current_session, sidecar_discard_artifact, sidecar_discard_patch, sidecar_end_session,
        sidecar_get_applied_artifacts, sidecar_get_applied_patches, sidecar_get_artifact, sidecar_get_config,
        sidecar_get_current_pending_artifacts, sidecar_get_current_staged_patches, sidecar_get_injectable_context, sidecar_get_patch,
        sidecar_get_pending_artifacts, sidecar_get_session_log, sidecar_get_session_meta, sidecar_get_session_state,
        sidecar_get_staged_patches, sidecar_initialize, sidecar_list_sessions, sidecar_preview_artifact,
        sidecar_regenerate_artifacts, sidecar_regenerate_patch, sidecar_resume_session, sidecar_set_config,
        sidecar_shutdown, sidecar_start_session, sidecar_status, sidecar_update_patch_message,
        // ── vault (8 commands) ──
        vault_add, vault_delete, vault_get_value, vault_list,
        vault_resolve, vault_update, vault_update_status, vault_validate,
        // ── vuln_intel (15 commands) ──
        intel_add_feed, intel_batch_search_nuclei_templates, intel_delete_feed, intel_discover_all_nuclei,
        intel_fetch, intel_fetch_page, intel_get_cached, intel_list_feeds,
        intel_match_targets, intel_search, intel_search_github_poc, intel_search_nuclei_templates,
        intel_search_remote, intel_search_remote_page, intel_toggle_feed,
        // ── wiki (37 commands) ──
        kb_research_clear, kb_research_load, kb_research_save_turn, kb_research_set_status,
        vuln_link_add_poc, vuln_link_add_poc_full, vuln_link_add_scan, vuln_link_add_wiki,
        vuln_link_get, vuln_link_get_all, vuln_link_remove_poc, vuln_link_remove_scan,
        vuln_link_remove_wiki, vuln_link_update_poc, vuln_poc_list_cves, vuln_poc_list_unresearched,
        vuln_poc_set_verified, vuln_poc_stats, wiki_backlinks, wiki_changelog_list,
        wiki_create_cve, wiki_create_dir, wiki_delete, wiki_init,
        wiki_list, wiki_orphan_pages, wiki_pages_for_paths, wiki_pages_grouped,
        wiki_read, wiki_reindex, wiki_rename, wiki_search,
        wiki_search_db, wiki_stats, wiki_stats_full, wiki_suggest_for_cve,
        wiki_write,
        // ── workspace (135 commands) ──
        agent_logs_list, api_endpoints_list, api_endpoints_untested, audit_clear,
        audit_list, audit_log, clean_project_temp, conv_delete,
        conv_list, conv_load_messages, conv_load_preferences, conv_load_terminal_states,
        conv_load_timeline, conv_save, conv_save_batch, conv_save_messages,
        conv_save_preferences, conv_save_terminal_state, conv_save_timeline, custom_rules_delete,
        custom_rules_list, custom_rules_save_all, custom_rules_upsert, delete_project_config,
        delete_rule, delete_skill, directory_entry_list, fingerprints_list,
        get_pentest_config, get_project_config, get_zap_discovered_paths, init_project_structure,
        js_analysis_list, list_capture_files, list_captures, list_directory,
        list_path_completions, list_project_configs, list_prompts, list_rules,
        list_skill_files, list_skills, list_workspace_files, load_project_workspace,
        match_pocs_for_target, method_delete_project, method_list_projects, method_list_templates,
        method_load_project, method_start_project, method_update_item, notes_add,
        notes_delete, notes_list, notes_update, nuclei_cancel,
        oplog_count, oplog_list, oplog_list_by_target, oplog_list_by_type,
        oplog_search, output_detect_tool, output_parse, output_parse_and_store,
        passive_scans_by_url, passive_scans_global, passive_scans_list, passive_scans_stats,
        passive_scans_vulnerable, plan_create, plan_delete, plan_get,
        plan_list, plan_list_active, plan_update_context, plan_update_status,
        plan_update_steps, project_export, project_import, read_file_as_base64,
        read_project_file, read_prompt, read_rule_body, read_skill,
        read_skill_body, read_skill_file, read_workspace_file, recording_delete,
        recording_list, recording_load, recording_save, save_pentest_config,
        save_project, save_project_workspace, save_rule, save_skill,
        scan_feroxbuster, scan_nuclei_targeted, scan_queue_clear_completed, scan_queue_list,
        scan_queue_remove, scan_queue_save_all, scan_queue_upsert, scan_whatweb,
        search_logs_list, sensitive_scan_apply_verdicts, sensitive_scan_clear, sensitive_scan_confirm,
        sensitive_scan_default_paths, sensitive_scan_results, sensitive_scan_start, sensitive_scan_status,
        sensitive_scan_stop, stat_workspace_file, target_add, target_assets_list,
        target_batch_add, target_clear_all, target_delete, target_list,
        target_security_overview, target_update, target_update_status, terminal_logs_list,
        unwatch_all_files, unwatch_file, watch_file, wordlist_deduplicate,
        wordlist_delete, wordlist_import, wordlist_list, wordlist_merge,
        wordlist_path, wordlist_preview, write_workspace_file,
    ])
}
