//! Wiki / vulnerability knowledge-base commands.
//!
//! Originally a single ~1300-line file mixing five distinct concerns; split
//! by feature surface so each domain owns its own file:
//!
//! - [`pages`]       — filesystem-backed page CRUD (`wiki_init`,
//!   `wiki_list`, `wiki_read`, `wiki_write`, `wiki_delete`, `wiki_rename`,
//!   `wiki_create_dir`, `wiki_create_cve`, `wiki_reindex`).  Owns the
//!   YAML-frontmatter parser and the on-disk schema docs.
//! - [`search`]      — `wiki_search` (filesystem grep) and `wiki_search_db`
//!   / `wiki_stats` (Postgres FTS).
//! - [`vuln_links`]  — vulnerability ↔ wiki / PoC / scan history CRUD
//!   (`vuln_link_*` and `vuln_poc_*` commands).
//! - [`kb_research`] — research-log persistence per CVE.
//! - [`dashboard`]   — Karpathy-style wiki overview: page groupings,
//!   changelog, backlinks, orphan pages, full stats.
//!
//! Public command names are unchanged; `lib.rs` references them as
//! `tools::wiki::<name>`, so this module re-exports each command at the
//! crate-visible path.

mod dashboard;
mod kb_research;
mod pages;
mod search;
mod vuln_links;

use std::path::PathBuf;

// Public re-exports — every `#[tauri::command]` function defined under
// `tools::wiki::*` must be reachable at this exact path because
// `lib.rs::generate_handler!` references each one as `tools::wiki::name`.
//
// Note: we re-export both the function AND the matching `__cmd__$name`
// macro generated by `#[tauri::command]`. The handler-generation macro
// expands `tools::wiki::wiki_init` into `tools::wiki::__cmd__wiki_init!(…)`,
// so without the macro re-export the build fails with "could not find
// `__cmd__wiki_init` in `wiki`".
pub use dashboard::{
    wiki_backlinks, wiki_changelog_list, wiki_orphan_pages, wiki_pages_for_paths,
    wiki_pages_grouped, wiki_stats_full, wiki_suggest_for_cve, __cmd__wiki_backlinks,
    __cmd__wiki_changelog_list, __cmd__wiki_orphan_pages, __cmd__wiki_pages_for_paths,
    __cmd__wiki_pages_grouped, __cmd__wiki_stats_full, __cmd__wiki_suggest_for_cve,
};
pub use kb_research::{
    kb_research_clear, kb_research_load, kb_research_save_turn, kb_research_set_status,
    __cmd__kb_research_clear, __cmd__kb_research_load, __cmd__kb_research_save_turn,
    __cmd__kb_research_set_status,
};
pub use pages::{
    wiki_create_cve, wiki_create_dir, wiki_delete, wiki_init, wiki_list, wiki_read, wiki_reindex,
    wiki_rename, wiki_write, __cmd__wiki_create_cve, __cmd__wiki_create_dir, __cmd__wiki_delete,
    __cmd__wiki_init, __cmd__wiki_list, __cmd__wiki_read, __cmd__wiki_reindex, __cmd__wiki_rename,
    __cmd__wiki_write,
};
pub use search::{
    wiki_search, wiki_search_db, wiki_stats, __cmd__wiki_search, __cmd__wiki_search_db,
    __cmd__wiki_stats,
};
pub use vuln_links::{
    vuln_link_add_poc, vuln_link_add_poc_full, vuln_link_add_scan, vuln_link_add_wiki,
    vuln_link_get, vuln_link_get_all, vuln_link_remove_poc, vuln_link_remove_scan,
    vuln_link_remove_wiki, vuln_link_update_poc, vuln_poc_list_cves, vuln_poc_list_unresearched,
    vuln_poc_set_verified, vuln_poc_stats, __cmd__vuln_link_add_poc, __cmd__vuln_link_add_poc_full,
    __cmd__vuln_link_add_scan, __cmd__vuln_link_add_wiki, __cmd__vuln_link_get,
    __cmd__vuln_link_get_all, __cmd__vuln_link_remove_poc, __cmd__vuln_link_remove_scan,
    __cmd__vuln_link_remove_wiki, __cmd__vuln_link_update_poc, __cmd__vuln_poc_list_cves,
    __cmd__vuln_poc_list_unresearched, __cmd__vuln_poc_set_verified, __cmd__vuln_poc_stats,
};

/// Wiki file extensions recognised by the on-disk filtering / search code.
///
/// Keeping the list central (here rather than in `pages` or `search`) means
/// both filesystem traversal and FTS-style code paths stay consistent when
/// extensions are added.
pub(super) const WIKI_EXTENSIONS: &[&str] = &[
    ".md", ".txt", ".py", ".sh", ".bash", ".zsh", ".go", ".rs", ".rb", ".pl",
    ".js", ".ts", ".jsx", ".tsx", ".c", ".cpp", ".h", ".hpp", ".java", ".cs",
    ".swift", ".kt", ".lua", ".r", ".ps1", ".bat", ".cmd", ".php", ".html",
    ".css", ".xml", ".json", ".yaml", ".yml", ".toml", ".ini", ".conf", ".cfg",
    ".sql", ".graphql", ".proto", ".dockerfile", ".nse",
];

/// Predicate: is this filename one of our supported wiki content files?
///
/// Matches by extension (case-insensitive) plus a small set of well-known
/// extensionless filenames (Dockerfile, Makefile, Rakefile).
pub(super) fn is_wiki_file(name: &str) -> bool {
    let lower = name.to_lowercase();
    WIKI_EXTENSIONS.iter().any(|ext| lower.ends_with(ext))
        || lower == "dockerfile"
        || lower == "makefile"
        || lower == "rakefile"
}

/// Predicate: is this filename one whose content we can grep through?
///
/// Currently identical to [`is_wiki_file`] — kept as a separate name so the
/// two intents (storage filter vs. text-search filter) remain
/// distinguishable if they ever diverge.
pub(super) fn is_text_searchable(name: &str) -> bool {
    is_wiki_file(name)
}

/// Resolve the on-disk wiki root: `<app-data>/wiki`.
///
/// Panics if the home directory can't be determined — at this point the
/// app has already started, so this is a configuration bug rather than
/// something to recover from.
pub(super) fn wiki_base_dir() -> PathBuf {
    golish_core::paths::app_data_base()
        .expect("cannot resolve home directory")
        .join("wiki")
}
