/**
 * Re-exports of LLM model ID constants.
 *
 * The actual constants live in `models.generated.ts`, which is generated by
 * `frontend/scripts/generate-model-constants.mjs` from the JSON resources in
 * `resources/llm-models/<provider>.json` plus the const-key map in
 * `frontend/scripts/model-const-keys.json`.
 *
 * Editing this file by hand is fine for new exports or aggregator helpers,
 * but the per-provider `*_MODELS` objects below are derived data — to add /
 * remove / rename a model, update the JSON resource and (if a TS constant is
 * needed) the const-key map. The generator runs via the `predev` / `prebuild`
 * npm scripts so the generated file stays fresh.
 *
 * See `docs/design/2026-05-25-llm-models-json-driven.md` for the rationale.
 */

export {
  ANTHROPIC_MODELS,
  DEEPSEEK_MODELS,
  GEMINI_MODELS,
  GROQ_MODELS,
  NVIDIA_MODELS,
  OLLAMA_MODELS,
  OPENAI_MODELS,
  VERTEX_AI_MODELS,
  VERTEX_GEMINI_MODELS,
  XAI_MODELS,
  XIAOMI_MODELS,
  ZAI_SDK_MODELS,
} from "./models.generated";
