// Cross-IPC types generated by ts-rs into @/lib/generated (AGENTS.md I5).
// Edit the Rust source in backend/crates/golish-*, then run `just gen-types`.
// Do not hand-edit files under @/lib/generated.
import type { AgentMode } from "@/lib/generated/AgentMode";
import type { AiProvider } from "@/lib/generated/AiProvider";
import type { ApiRequestStatsSnapshot } from "@/lib/generated/ApiRequestStatsSnapshot";
import type { ApprovalDecision } from "@/lib/generated/ApprovalDecision";
import type { ApprovalPattern } from "@/lib/generated/ApprovalPattern";
import type { AuditEntry } from "@/lib/generated/AuditEntry";
import type { DbTokenUsageStats } from "@/lib/generated/DbTokenUsageStats";
import type { GeneratedAiEvent } from "@/lib/generated/GeneratedAiEvent";
import type { MemoryEntry } from "@/lib/generated/MemoryEntry";
import type { ProviderConfig as GeneratedProviderConfig } from "@/lib/generated/ProviderConfig";
import type { ProviderRequestStatsSnapshot } from "@/lib/generated/ProviderRequestStatsSnapshot";
import type { ReasoningEffort } from "@/lib/generated/ReasoningEffort";
import type { ReconToolCheck } from "@/lib/generated/ReconToolCheck";
import type { RiskLevel } from "@/lib/generated/RiskLevel";
import type { RuleInfo } from "@/lib/generated/RuleInfo";
import type { SkillInfo } from "@/lib/generated/SkillInfo";
import type { SubAgentInfo } from "@/lib/generated/SubAgentInfo";
import type { ToolApprovalConfig } from "@/lib/generated/ToolApprovalConfig";
import type { ToolCallStats } from "@/lib/generated/ToolCallStats";
import type { ToolSource } from "@/lib/generated/ToolSource";
import type { ToolStatus } from "@/lib/generated/ToolStatus";
import type { VisionCapabilities } from "@/lib/generated/VisionCapabilities";

export type {
  AgentMode,
  AiProvider,
  ApiRequestStatsSnapshot,
  ApprovalDecision,
  ApprovalPattern,
  AuditEntry,
  DbTokenUsageStats,
  GeneratedAiEvent,
  MemoryEntry,
  ProviderRequestStatsSnapshot,
  ReasoningEffort,
  ReconToolCheck,
  RiskLevel,
  RuleInfo,
  SkillInfo,
  SubAgentInfo,
  ToolApprovalConfig,
  ToolCallStats,
  ToolSource,
  ToolStatus,
  VisionCapabilities,
};

export interface ProjectSettings {
  provider: AiProvider | null;
  model: string | null;
  agent_mode: AgentMode | null;
}

export interface AiConfig {
  workspace: string;
  provider: AiProvider;
  model: string;
  apiKey: string;
}

/**
 * User-supplied per-(provider, model) override forwarded to the backend.
 *
 * Mirror of `backend/crates/golish-settings/src/schema/ai.rs::ModelOverride`
 * and the frontend's {@link ModelOverride} in `lib/settings/types.ts`.
 *
 * The backend uses this to:
 * - Toggle `quirks.reasoning_handling` between `Standard` and `AlwaysContent`
 * - Inject `chat_template_kwargs.enable_thinking=false` on the outgoing request
 * - Apply `reasoning.effort` / `max_tokens` overrides where supported
 */
export interface ProviderModelOverride {
  thinking?: boolean;
  reasoning_effort?: string;
  max_tokens?: number;
  context_window?: number;
  stream_debug?: boolean;
}

interface ProviderConfigBase {
  /** Optional per-model override applied alongside provider defaults. */
  model_override?: ProviderModelOverride;
}

// The provider variants come from the ts-rs-generated `ProviderConfig`
// (Rust source of truth; settings-backed fields are skipped there). The
// `model_override` field is re-attached here via `ProviderConfigBase` so the
// generated graph doesn't need to pull in `ModelOverride`.
export type ProviderConfig = ProviderConfigBase & GeneratedProviderConfig;

interface AiEventEnvelope {
  session_id: string;
  seq?: number;
  ts?: string;
}

/**
 * AiEvent intersected with the transport envelope fields added by
 * the Tauri event system.
 */
export type AiEvent = AiEventEnvelope & GeneratedAiEvent;

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export interface WorkflowInfo {
  name: string;
  description: string;
}

export interface SubAgentModelOverride {
  provider: AiProvider;
  model: string;
}

export interface SessionAiConfigInfo {
  provider: string;
  model: string;
}

export interface VertexAiEnvConfig {
  credentials_path: string | null;
  project_id: string | null;
  location: string | null;
}

/**
 * Role of a message in the conversation (simplified for Golish).
 */
export type SessionMessageRole = "user" | "assistant" | "system" | "tool";

/**
 * A simplified message format for Golish sessions.
 */
export interface SessionMessage {
  role: SessionMessageRole;
  content: string;
  tool_call_id?: string | null;
  tool_name?: string | null;
  tokens_used?: number | null;
}

/**
 * Golish session snapshot containing conversation data.
 */
export interface SessionSnapshot {
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  transcript: string[];
  messages: SessionMessage[];
  sidecar_session_id: string | null;
  total_tokens?: bigint | null;
  agent_mode?: string | null;
}

/**
 * Session listing information for display.
 */
export interface SessionListingInfo {
  identifier: string;
  path: string;
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  first_prompt_preview: string | null;
  first_reply_preview: string | null;
  status: string | null;
  title: string | null;
}

export type { TaskPlan } from "@/store/types/plan";

/**
 * A part of a multi-modal prompt payload.
 */
export type PromptPart =
  | { type: "text"; text: string }
  | {
      type: "image";
      data: string;
      media_type?: string | null;
      filename?: string | null;
    };

/**
 * A multi-modal prompt payload containing text and/or image parts.
 *
 * This is the format expected by the `send_ai_prompt_with_attachments`
 * command. For text-only prompts, the existing `send_ai_prompt_session`
 * can still be used.
 */
export interface PromptPayload {
  parts: PromptPart[];
}

export type TextPart = Extract<PromptPart, { type: "text" }>;
export type ImagePart = Extract<PromptPart, { type: "image" }>;

export interface AgentFileInfo {
  id: string;
  name: string;
  description: string;
  path: string;
  source: "built-in" | "file";
  scope: "global" | "project" | "built-in";
  is_system: boolean;
  model: string | null;
  allowed_tools: string[];
  max_iterations: number;
  timeout_secs: number | null;
  idle_timeout_secs: number | null;
  readonly: boolean;
  is_background: boolean;
  temperature: number | null;
  max_tokens: number | null;
  top_p: number | null;
}

export const DEFAULT_AI_CONFIG = {
  provider: "openrouter" as AiProvider,
  model: "anthropic/claude-opus-4.5",
};
