// Type definitions previously generated by `ts-rs` are inlined below
// (M2.5 codegen retirement). When changing any of these, mirror the
// edit in the corresponding Rust struct/enum in
// `backend/crates/golish-*` to keep both sides in lockstep.

/**
 * AI provider selection.
 */
export type AiProvider =
  | "vertex_ai"
  | "vertex_gemini"
  | "openrouter"
  | "anthropic"
  | "openai"
  | "ollama"
  | "gemini"
  | "groq"
  | "xai"
  | "zai_sdk"
  | "nvidia"
  | "deepseek"
  | "xiaomi";

/**
 * Reasoning effort level for models that support it (e.g., OpenAI o-series, GPT-5).
 */
export type ReasoningEffort = "low" | "medium" | "high" | "extra_high";

/**
 * Risk level for a tool operation.
 */
export type RiskLevel = "low" | "medium" | "high" | "critical";

export interface ProviderRequestStatsSnapshot {
  requests: bigint;
  last_sent_at: bigint | null;
  last_received_at: bigint | null;
}

export interface ApiRequestStatsSnapshot {
  providers: { [key: string]: ProviderRequestStatsSnapshot };
}

export interface ProjectSettings {
  provider: AiProvider | null;
  model: string | null;
  agent_mode: AgentMode | null;
}

export interface AiConfig {
  workspace: string;
  provider: AiProvider;
  model: string;
  apiKey: string;
}

/**
 * User-supplied per-(provider, model) override forwarded to the backend.
 *
 * Mirror of `backend/crates/golish-settings/src/schema/ai.rs::ModelOverride`
 * and the frontend's {@link ModelOverride} in `lib/settings/types.ts`.
 *
 * The backend uses this to:
 * - Toggle `quirks.reasoning_handling` between `Standard` and `AlwaysContent`
 * - Inject `chat_template_kwargs.enable_thinking=false` on the outgoing request
 * - Apply `reasoning.effort` / `max_tokens` overrides where supported
 */
export interface ProviderModelOverride {
  thinking?: boolean;
  reasoning_effort?: string;
  max_tokens?: number;
  context_window?: number;
  stream_debug?: boolean;
}

interface ProviderConfigBase {
  /** Optional per-model override applied alongside provider defaults. */
  model_override?: ProviderModelOverride;
}

export type ProviderConfig = ProviderConfigBase &
  (
    | {
        provider: "vertex_ai";
        workspace: string;
        model: string;
        credentials_path: string | null;
        project_id: string;
        location: string;
      }
    | {
        provider: "vertex_gemini";
        workspace: string;
        model: string;
        credentials_path: string | null;
        project_id: string;
        location: string;
      }
    | {
        provider: "openrouter";
        workspace: string;
        model: string;
        api_key: string;
        provider_preferences?: Record<string, unknown>;
      }
    | {
        provider: "openai";
        workspace: string;
        model: string;
        api_key: string;
        base_url?: string;
        reasoning_effort?: string;
      }
    | {
        provider: "anthropic";
        workspace: string;
        model: string;
        api_key: string;
      }
    | {
        provider: "ollama";
        workspace: string;
        model: string;
        base_url?: string;
      }
    | {
        provider: "gemini";
        workspace: string;
        model: string;
        api_key: string;
      }
    | {
        provider: "groq";
        workspace: string;
        model: string;
        api_key: string;
      }
    | {
        provider: "xai";
        workspace: string;
        model: string;
        api_key: string;
      }
    | {
        provider: "zai_sdk";
        workspace: string;
        model: string;
        api_key: string;
        base_url?: string;
      }
    | {
        provider: "nvidia";
        workspace: string;
        model: string;
        api_key: string;
        base_url?: string;
      }
    | {
        provider: "deepseek";
        workspace: string;
        model: string;
        api_key: string;
        base_url?: string;
      }
    | {
        provider: "xiaomi";
        workspace: string;
        model: string;
        api_key: string;
        region?: string;
        default_protocol?: string;
        base_url?: string;
        anthropic_base_url?: string;
      }
  );

import type { JsonValue } from "@/lib/serde_json/JsonValue";
import type { PlanStep, PlanSummary } from "@/store/types/plan";

/**
 * Approval pattern/statistics for a specific tool.
 */
export interface ApprovalPattern {
  tool_name: string;
  total_requests: number;
  approvals: number;
  denials: number;
  always_allow: boolean;
  last_updated: string;
  justifications: string[];
}

/**
 * Source of a tool call - indicates where the tool request originated.
 */
export type ToolSource =
  | { type: "main" }
  | { type: "sub_agent"; agent_id: string; agent_name: string }
  | {
      type: "workflow";
      workflow_id: string;
      workflow_name: string;
      step_name: string | null;
      step_index: number | null;
    };

interface AiEventEnvelope {
  session_id: string;
  seq?: number;
  ts?: string;
}

/**
 * Inner AI event union mirroring the backend `AiEvent` enum
 * (`backend/crates/golish-agent-bridge`). Note the generated type
 * uses `bigint` for duration_ms / tokens_before; at runtime Tauri
 * serializes these as `number`, so callers can safely treat them as
 * `number` — TypeScript structural typing handles this transparently.
 */
export type GeneratedAiEvent =
  | { type: "started"; turn_id: string }
  | { type: "user_message"; content: string }
  | { type: "system_hooks_injected"; hooks: string[] }
  | { type: "text_delta"; delta: string; accumulated: string }
  | {
      type: "tool_request";
      tool_name: string;
      args: JsonValue;
      request_id: string;
      source: ToolSource;
    }
  | {
      type: "tool_intent_observation";
      request_id: string;
      tool_name: string;
      source: "native_tool_call" | "textual_xml" | "textual_json" | "recovered" | string;
      decision: "allow" | "require_approval" | "require_human_answer" | "reject" | string;
      reason: string | null;
      raw_preview: string | null;
    }
  | {
      type: "tool_approval_request";
      request_id: string;
      tool_name: string;
      args: JsonValue;
      stats: ApprovalPattern | null;
      risk_level: RiskLevel;
      can_learn: boolean;
      suggestion: string | null;
      source: ToolSource;
    }
  | {
      type: "tool_auto_approved";
      request_id: string;
      tool_name: string;
      args: JsonValue;
      reason: string;
      source: ToolSource;
    }
  | {
      type: "tool_denied";
      request_id: string;
      tool_name: string;
      args: JsonValue;
      reason: string;
      source: ToolSource;
    }
  | {
      type: "tool_result";
      tool_name: string;
      result: JsonValue;
      success: boolean;
      request_id: string;
      source: ToolSource;
    }
  | {
      type: "tool_output_chunk";
      request_id: string;
      tool_name: string;
      chunk: string;
      stream: string;
      source: ToolSource;
    }
  | { type: "reasoning"; content: string }
  | {
      type: "completed";
      response: string;
      reasoning: string | null;
      input_tokens: number | null;
      output_tokens: number | null;
      duration_ms: bigint | null;
    }
  | { type: "error"; message: string; error_type: string }
  | {
      type: "ask_human_request";
      request_id: string;
      question: string;
      input_type: string;
      options: string[];
      context: string;
    }
  | {
      type: "ask_human_response";
      request_id: string;
      response: string;
      skipped: boolean;
    }
  | {
      type: "sub_agent_started";
      agent_id: string;
      agent_name: string;
      task: string;
      depth: number;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_tool_request";
      agent_id: string;
      tool_name: string;
      args: JsonValue;
      request_id: string;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_tool_result";
      agent_id: string;
      tool_name: string;
      success: boolean;
      result: JsonValue;
      request_id: string;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_text_delta";
      agent_id: string;
      delta: string;
      accumulated: string;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_reasoning";
      agent_id: string;
      delta: string;
      accumulated: string;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_completed";
      agent_id: string;
      response: string;
      duration_ms: bigint;
      parent_request_id: string;
    }
  | {
      type: "sub_agent_error";
      agent_id: string;
      error: string;
      parent_request_id: string;
    }
  | {
      type: "context_warning";
      utilization: number;
      total_tokens: number;
      max_tokens: number;
    }
  | {
      type: "tool_response_truncated";
      tool_name: string;
      original_tokens: number;
      truncated_tokens: number;
    }
  | { type: "warning"; message: string }
  | {
      type: "compaction_started";
      tokens_before: bigint;
      messages_before: number;
    }
  | {
      type: "compaction_completed";
      tokens_before: bigint;
      messages_before: number;
      messages_after: number;
      summary_length: number;
      summary: string | null;
      summarizer_input: string | null;
    }
  | {
      type: "compaction_failed";
      tokens_before: bigint;
      messages_before: number;
      error: string;
      summarizer_input: string | null;
    }
  | {
      type: "loop_warning";
      tool_name: string;
      current_count: number;
      max_count: number;
      message: string;
    }
  | {
      type: "loop_blocked";
      tool_name: string;
      repeat_count: number;
      max_count: number;
      message: string;
    }
  | {
      type: "max_iterations_reached";
      iterations: number;
      max_iterations: number;
      message: string;
    }
  | {
      type: "workflow_started";
      workflow_id: string;
      workflow_name: string;
      session_id: string;
    }
  | {
      type: "workflow_step_started";
      workflow_id: string;
      step_name: string;
      step_index: number;
      total_steps: number;
    }
  | {
      type: "workflow_step_completed";
      workflow_id: string;
      step_name: string;
      output: string | null;
      duration_ms: bigint;
    }
  | {
      type: "workflow_completed";
      workflow_id: string;
      final_output: string;
      total_duration_ms: bigint;
    }
  | {
      type: "workflow_error";
      workflow_id: string;
      step_name: string | null;
      error: string;
    }
  | {
      type: "plan_updated";
      version: number;
      summary: PlanSummary;
      steps: PlanStep[];
      explanation: string | null;
    }
  | {
      type: "server_tool_started";
      request_id: string;
      tool_name: string;
      input: JsonValue;
    }
  | {
      type: "web_search_result";
      request_id: string;
      results: JsonValue;
    }
  | {
      type: "web_fetch_result";
      request_id: string;
      url: string;
      content_preview: string;
    }
  | {
      type: "prompt_generation_started";
      agent_id: string;
      parent_request_id: string;
      architect_system_prompt: string;
      architect_user_message: string;
    }
  | {
      type: "prompt_generation_completed";
      agent_id: string;
      parent_request_id: string;
      generated_prompt: string | null;
      success: boolean;
      duration_ms: bigint;
    }
  | { type: "task_progress"; task_id: string; status: string; message: string }
  | {
      type: "subtask_created";
      task_id: string;
      subtask_id: string;
      title: string;
      agent: string | null;
    }
  | {
      type: "subtask_completed";
      task_id: string;
      subtask_id: string;
      title: string;
      result: string;
    }
  | {
      type: "subtask_waiting_for_input";
      task_id: string;
      subtask_id: string;
      title: string;
      prompt: string;
    }
  | {
      type: "subtask_user_input";
      task_id: string;
      subtask_id: string;
      input: string;
    }
  | {
      type: "task_resumed";
      task_id: string;
      subtask_index: number;
      total_subtasks: number;
    }
  | {
      type: "enricher_result";
      task_id: string;
      subtask_id: string;
      context_added: string;
    };

/**
 * AiEvent intersected with the transport envelope fields added by
 * the Tauri event system.
 */
export type AiEvent = AiEventEnvelope & GeneratedAiEvent;

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export interface WorkflowInfo {
  name: string;
  description: string;
}

export interface SubAgentInfo {
  id: string;
  name: string;
  description: string;
  model_override: [string, string] | null;
}

export interface SubAgentModelOverride {
  provider: AiProvider;
  model: string;
}

export interface SessionAiConfigInfo {
  provider: string;
  model: string;
}

export interface ToolStatus {
  name: string;
  installed: boolean;
}

export interface ReconToolCheck {
  tools: ToolStatus[];
  all_ready: boolean;
  missing: string[];
}

export interface VertexAiEnvConfig {
  credentials_path: string | null;
  project_id: string | null;
  location: string | null;
}

export interface VertexAiConfig {
  workspace: string;
  credentialsPath: string;
  projectId: string;
  location: string;
  model: string;
}

export interface OpenAiConfig {
  workspace: string;
  model: string;
  apiKey: string;
  baseUrl?: string;
  reasoningEffort?: ReasoningEffort;
}

export type AgentMode = "default" | "auto-approve" | "planning";

/**
 * User's decision on an approval request.
 */
export interface ApprovalDecision {
  request_id: string;
  approved: boolean;
  reason: string | null;
  remember: boolean;
  always_allow: boolean;
}

/**
 * Role of a message in the conversation (simplified for Golish).
 */
export type SessionMessageRole = "user" | "assistant" | "system" | "tool";

/**
 * A simplified message format for Golish sessions.
 */
export interface SessionMessage {
  role: SessionMessageRole;
  content: string;
  tool_call_id?: string | null;
  tool_name?: string | null;
  tokens_used?: number | null;
}

/**
 * Golish session snapshot containing conversation data.
 */
export interface SessionSnapshot {
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  transcript: string[];
  messages: SessionMessage[];
  sidecar_session_id: string | null;
  total_tokens?: bigint | null;
  agent_mode?: string | null;
}

/**
 * Session listing information for display.
 */
export interface SessionListingInfo {
  identifier: string;
  path: string;
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  first_prompt_preview: string | null;
  first_reply_preview: string | null;
  status: string | null;
  title: string | null;
}

/**
 * Configuration for tool approval behavior.
 */
export interface ToolApprovalConfig {
  always_allow: string[];
  always_require_approval: string[];
  pattern_learning_enabled: boolean;
  min_approvals: number;
  approval_threshold: number;
}

export type { TaskPlan } from "@/store/types/plan";

export interface VisionCapabilities {
  supports_vision: boolean;
  max_image_size_bytes: number;
  supported_formats: string[];
}

/**
 * A part of a multi-modal prompt payload.
 */
export type PromptPart =
  | { type: "text"; text: string }
  | {
      type: "image";
      data: string;
      media_type?: string | null;
      filename?: string | null;
    };

/**
 * A multi-modal prompt payload containing text and/or image parts.
 *
 * This is the format expected by the `send_ai_prompt_with_attachments`
 * command. For text-only prompts, the existing `send_ai_prompt_session`
 * can still be used.
 */
export interface PromptPayload {
  parts: PromptPart[];
}

export type TextPart = Extract<PromptPart, { type: "text" }>;
export type ImagePart = Extract<PromptPart, { type: "image" }>;

export interface CommitMessageResponse {
  summary: string;
  description: string;
}

export interface ToolCallStats {
  name: string;
  total_count: number;
  total_duration_ms: number;
  avg_duration_ms: number;
}

export interface DbTokenUsageStats {
  total_tokens_in: number;
  total_tokens_out: number;
  total_cost_in: number;
  total_cost_out: number;
}

export interface AuditEntry {
  id: number;
  action: string;
  category: string;
  details: string;
  entity_type: string | null;
  entity_id: string | null;
  project_path: string | null;
  created_at: string;
}

export interface MemoryEntry {
  id: string;
  content: string;
  mem_type: string;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface AgentFileInfo {
  id: string;
  name: string;
  description: string;
  path: string;
  source: "built-in" | "file";
  scope: "global" | "project" | "built-in";
  is_system: boolean;
  model: string | null;
  allowed_tools: string[];
  max_iterations: number;
  timeout_secs: number | null;
  idle_timeout_secs: number | null;
  readonly: boolean;
  is_background: boolean;
  temperature: number | null;
  max_tokens: number | null;
  top_p: number | null;
}

export interface SkillInfo {
  name: string;
  path: string;
  source: "global" | "project";
  description: string;
  license: string | null;
  compatibility: string | null;
  metadata: Record<string, string> | null;
  allowed_tools: string[] | null;
  has_scripts: boolean;
  has_references: boolean;
  has_assets: boolean;
}

export interface RuleInfo {
  name: string;
  path: string;
  source: "global" | "project";
  description: string;
  globs: string | null;
  always_apply: boolean;
}

export const DEFAULT_AI_CONFIG = {
  provider: "openrouter" as AiProvider,
  model: "anthropic/claude-opus-4.5",
};
