export type { RiskLevel } from "../generated/RiskLevel";
export type { AiProvider } from "../generated/AiProvider";

export interface ProjectSettings {
  provider: AiProvider | null;
  model: string | null;
  agent_mode: AgentMode | null;
}

export interface AiConfig {
  workspace: string;
  provider: AiProvider;
  model: string;
  apiKey: string;
}

export type ProviderConfig =
  | {
      provider: "vertex_ai";
      workspace: string;
      model: string;
      credentials_path: string | null;
      project_id: string;
      location: string;
    }
  | {
      provider: "vertex_gemini";
      workspace: string;
      model: string;
      credentials_path: string | null;
      project_id: string;
      location: string;
    }
  | {
      provider: "openrouter";
      workspace: string;
      model: string;
      api_key: string;
      provider_preferences?: Record<string, unknown>;
    }
  | {
      provider: "openai";
      workspace: string;
      model: string;
      api_key: string;
      base_url?: string;
      reasoning_effort?: string;
    }
  | {
      provider: "anthropic";
      workspace: string;
      model: string;
      api_key: string;
    }
  | {
      provider: "ollama";
      workspace: string;
      model: string;
      base_url?: string;
    }
  | {
      provider: "gemini";
      workspace: string;
      model: string;
      api_key: string;
    }
  | {
      provider: "groq";
      workspace: string;
      model: string;
      api_key: string;
    }
  | {
      provider: "xai";
      workspace: string;
      model: string;
      api_key: string;
    }
  | {
      provider: "zai_sdk";
      workspace: string;
      model: string;
      api_key: string;
      base_url?: string;
    }
  | {
      provider: "nvidia";
      workspace: string;
      model: string;
      api_key: string;
      base_url?: string;
    };

export type { ApprovalPattern } from "@/lib/generated";

export interface ProviderRequestStats {
  requests: number;
  last_sent_at: number | null;
  last_received_at: number | null;
}

export interface ApiRequestStatsSnapshot {
  providers: Record<string, ProviderRequestStats>;
}

export type { ToolSource } from "@/lib/generated";

import type { AiEvent as GeneratedAiEvent } from "@/lib/generated";

interface AiEventEnvelope {
  session_id: string;
  seq?: number;
  ts?: string;
}

/// AiEvent from the backend, intersected with the transport envelope fields
/// added by the Tauri event system. The inner union is generated by ts-rs
/// from the Rust `AiEvent` enum — keeping the two in sync automatically.
///
/// Note: the generated type uses `bigint` for duration_ms / tokens_before;
/// at runtime Tauri serializes these as `number`, so callers can safely treat
/// them as `number`. TypeScript structural typing handles this transparently.
export type AiEvent = AiEventEnvelope & GeneratedAiEvent;

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export interface WorkflowInfo {
  name: string;
  description: string;
}

export interface SubAgentInfo {
  id: string;
  name: string;
  description: string;
  model_override: [string, string] | null;
}

export interface SubAgentModelOverride {
  provider: AiProvider;
  model: string;
}

export interface SessionAiConfigInfo {
  provider: string;
  model: string;
}

export interface ToolStatus {
  name: string;
  installed: boolean;
}

export interface ReconToolCheck {
  tools: ToolStatus[];
  all_ready: boolean;
  missing: string[];
}

export interface VertexAiEnvConfig {
  credentials_path: string | null;
  project_id: string | null;
  location: string | null;
}

export interface VertexAiConfig {
  workspace: string;
  credentialsPath: string;
  projectId: string;
  location: string;
  model: string;
}

export interface OpenAiConfig {
  workspace: string;
  model: string;
  apiKey: string;
  baseUrl?: string;
  reasoningEffort?: ReasoningEffort;
}

export type ReasoningEffort = "low" | "medium" | "high" | "extra_high";

export type AgentMode = "default" | "auto-approve" | "planning";

export type SessionMessageRole = "user" | "assistant" | "system" | "tool";

export interface SessionMessage {
  role: SessionMessageRole;
  content: string;
  tool_call_id?: string;
  tool_name?: string;
}

export interface SessionListingInfo {
  identifier: string;
  path: string;
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  first_prompt_preview?: string;
  first_reply_preview?: string;
  status?: "active" | "completed" | "abandoned";
  title?: string;
}

export interface SessionSnapshot {
  workspace_label: string;
  workspace_path: string;
  model: string;
  provider: string;
  started_at: string;
  ended_at: string;
  total_messages: number;
  distinct_tools: string[];
  transcript: string[];
  messages: SessionMessage[];
  agent_mode?: string;
}

export interface ToolApprovalConfig {
  always_allow: string[];
  always_require_approval: string[];
  pattern_learning_enabled: boolean;
  min_approvals: number;
  approval_threshold: number;
}

export interface ApprovalDecision {
  request_id: string;
  approved: boolean;
  reason?: string;
  remember: boolean;
  always_allow: boolean;
}

export interface TaskPlan {
  explanation: string | null;
  steps: Array<{
    step: string;
    status: "pending" | "in_progress" | "completed" | "cancelled" | "failed";
  }>;
  summary: {
    total: number;
    completed: number;
    in_progress: number;
    pending: number;
  };
  version: number;
  updated_at: string;
}

export interface VisionCapabilities {
  supports_vision: boolean;
  max_image_size_bytes: number;
  supported_formats: string[];
}

export interface TextPart {
  type: "text";
  text: string;
}

export interface ImagePart {
  type: "image";
  data: string;
  media_type?: string;
  filename?: string;
}

export type PromptPart = TextPart | ImagePart;

export interface PromptPayload {
  parts: PromptPart[];
}

export interface CommitMessageResponse {
  summary: string;
  description: string;
}

export interface ToolCallStats {
  name: string;
  total_count: number;
  total_duration_ms: number;
  avg_duration_ms: number;
}

export interface DbTokenUsageStats {
  total_tokens_in: number;
  total_tokens_out: number;
  total_cost_in: number;
  total_cost_out: number;
}

export interface AuditEntry {
  id: number;
  action: string;
  category: string;
  details: string;
  entity_type: string | null;
  entity_id: string | null;
  project_path: string | null;
  created_at: string;
}

export interface MemoryEntry {
  id: string;
  content: string;
  mem_type: string;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface AgentFileInfo {
  id: string;
  name: string;
  description: string;
  path: string;
  source: "built-in" | "file";
  scope: "global" | "project" | "built-in";
  is_system: boolean;
  model: string | null;
  allowed_tools: string[];
  max_iterations: number;
  timeout_secs: number | null;
  idle_timeout_secs: number | null;
  readonly: boolean;
  is_background: boolean;
  temperature: number | null;
  max_tokens: number | null;
  top_p: number | null;
}

export interface SkillInfo {
  name: string;
  path: string;
  source: "global" | "project";
  description: string;
  license: string | null;
  compatibility: string | null;
  metadata: Record<string, string> | null;
  allowed_tools: string[] | null;
  has_scripts: boolean;
  has_references: boolean;
  has_assets: boolean;
}

export interface RuleInfo {
  name: string;
  path: string;
  source: "global" | "project";
  description: string;
  globs: string | null;
  always_apply: boolean;
}

export const DEFAULT_AI_CONFIG = {
  provider: "openrouter" as AiProvider,
  model: "anthropic/claude-opus-4.5",
};
