/**
 * AI API — re-exports all AI session/provider/approval/persistence functions
 * through a unified entry point.
 */
export {
  initAiAgent,
  retryCompaction,
  sendPrompt,
  executeTool,
  getAvailableTools,
  getAvailableWorkflows,
  getAvailableSubAgents,
  setSubAgentModel,
  getSubAgentModel,
  clearSubAgentModel,
  shutdownAiAgent,
  onAiEvent,
  signalFrontendReady,
  isAiInitialized,
  updateAiWorkspace,
  clearAiConversation,
  getAiConversationLength,
  initAiSession,
  shutdownAiSession,
  cancelAiGeneration,
  isAiSessionInitialized,
  getSessionAiConfig,
  sendPromptSession,
  startWorkflow,
  runWorkflowToCompletion,
  runReconPipeline,
  checkReconTools,
  triggerAutoRecon,
  clearAiConversationSession,
  getAiConversationLengthSession,
  getOpenRouterApiKey,
  loadEnvFile,
} from "../ai/session";

export {
  getApprovalPatterns,
  getToolApprovalPattern,
  getHitlConfig,
  setHitlConfig,
  addToolAlwaysAllow,
  removeToolAlwaysAllow,
  resetApprovalPatterns,
  respondToToolApproval,
  calculateApprovalRate,
  qualifiesForAutoApprove,
  setAgentMode,
  setUseAgents,
  setExecutionMode,
  getExecutionMode,
  getProjectSettings,
  saveProjectModel,
  saveProjectAgentMode,
} from "../ai/approval";

export {
  listAiSessions,
  findAiSession,
  loadAiSession,
  exportAiSessionTranscript,
  setAiSessionPersistence,
  isAiSessionPersistenceEnabled,
  finalizeAiSession,
  restoreAiSession,
  restoreAiConversation,
  getPlan,
  getVisionCapabilities,
  getApiRequestStats,
  sendPromptWithAttachments,
  createTextPayload,
  hasImages,
  extractText,
  generateCommitMessage,
  getToolCallStats,
  getDbTokenUsageStats,
  getAuditLog,
  searchMemories,
  listRecentMemories,
  getMemoryCount,
  listAgentDefinitions,
  readAgentPrompt,
  saveAgentDefinition,
  deleteAgentDefinition,
  seedAgents,
  listSkills,
  readSkillBody,
  saveSkill,
  deleteSkill,
  listRules,
  readRuleBody,
  saveRule,
  deleteRule,
} from "../ai/persistence";

export {
  getVertexAiConfig,
  initClaudeOpus,
  initVertexAiAgent,
  initVertexClaudeOpus,
  getOpenAiApiKey,
  initOpenAiAgent,
  initAiAgentUnified,
  initWithAnthropic,
  initWithOllama,
  initWithGemini,
  initWithGroq,
  initWithXai,
  buildProviderConfig,
} from "../ai/providers";
