/**
 * AI API — re-exports all AI session/provider/approval/persistence functions
 * through a unified entry point.
 */

export {
  addToolAlwaysAllow,
  calculateApprovalRate,
  getApprovalPatterns,
  getExecutionMode,
  getHitlConfig,
  getProjectSettings,
  getToolApprovalPattern,
  qualifiesForAutoApprove,
  removeToolAlwaysAllow,
  resetApprovalPatterns,
  respondToToolApproval,
  saveProjectAgentMode,
  saveProjectModel,
  setAgentMode,
  setExecutionMode,
  setHitlConfig,
  setUseAgents,
} from "../ai/approval";
export {
  createTextPayload,
  deleteAgentDefinition,
  deleteRule,
  deleteSkill,
  exportAiSessionTranscript,
  extractText,
  finalizeAiSession,
  findAiSession,
  generateCommitMessage,
  getApiRequestStats,
  getAuditLog,
  getDbTokenUsageStats,
  getMemoryCount,
  getPlan,
  getToolCallStats,
  getVisionCapabilities,
  hasImages,
  isAiSessionPersistenceEnabled,
  listAgentDefinitions,
  listAiSessions,
  listRecentMemories,
  listRules,
  listSkills,
  loadAiSession,
  readAgentPrompt,
  readRuleBody,
  readSkillBody,
  restoreAiConversation,
  restoreAiSession,
  saveAgentDefinition,
  saveRule,
  saveSkill,
  searchMemories,
  seedAgents,
  sendPromptWithAttachments,
  setAiSessionPersistence,
} from "../ai/persistence";
export {
  buildProviderConfig,
  getOpenAiApiKey,
  getVertexAiConfig,
  initAiAgentUnified,
  initClaudeOpus,
  initOpenAiAgent,
  initVertexAiAgent,
  initVertexClaudeOpus,
  initWithAnthropic,
  initWithGemini,
  initWithGroq,
  initWithOllama,
  initWithXai,
} from "../ai/providers";
export {
  cancelAiGeneration,
  checkReconTools,
  clearAiConversation,
  clearAiConversationSession,
  clearSubAgentModel,
  executeTool,
  getAiConversationLength,
  getAiConversationLengthSession,
  getAvailableSubAgents,
  getAvailableTools,
  getAvailableWorkflows,
  getOpenRouterApiKey,
  getSessionAiConfig,
  getSubAgentModel,
  initAiAgent,
  initAiSession,
  isAiInitialized,
  isAiSessionInitialized,
  loadEnvFile,
  onAiEvent,
  retryCompaction,
  runReconPipeline,
  runWorkflowToCompletion,
  sendPrompt,
  sendPromptSession,
  setSubAgentModel,
  shutdownAiAgent,
  shutdownAiSession,
  signalFrontendReady,
  startWorkflow,
  triggerAutoRecon,
  updateAiWorkspace,
} from "../ai/session";
